const CHATTING_ACTIONS_TYPES = {
    "CHATTING_SEND" : "CHATTING_SEND",
    "CHOOSE_USER_CHAT" : "CHOOSE_USER_CHAT",
    "AXIOS_MESSAGE_CHAT_START": "AXIOS_MESSAGE_CHAT_START",
    "AXIOS_MESSAGE_CHAT_SUCCESS" : "AXIOS_MESSAGE_CHAT_SUCCESS",
    "AXIOS_MESSAGE_CHAT_FAILURE" : "AXIOS_MESSAGE_CHAT_FAILURE"
}

export default CHATTING_ACTIONS_TYPES;