 const UserActionTypes = {
    "SET_CURRENT_USER": "SET_CURRENT_USER",
    "USER_LOG_OUT" : "USER_LOG_OUT",
    "USER_UPDATE_INFORMATION": "USER_UPDATE_INFORMATION",
    "USER_UPDATE_SECONDARY" : "USER_UPDATE_SECONDARY",
    "USER_UPDATE_PRI" : "USER_UPDATE_PRI",
    "USER_UPDATE_ADDRESS": "USER_UPDATE_ADDRESS",
    "USER_UPDATE_INTERESTED" : "USER_UPDATE_INTERESTED"
}

export default UserActionTypes;